comment:
  layout: "condensed_header, diff, condensed_footer"
  behavior: default
  hide_project_coverage: false
  require_changes: false
  require_base: false
  require_head: true

coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 0%
    patch:
      default:
        informational: true
        target: auto
        threshold: 0%
