comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  hide_project_coverage: FALSE
  require_changes: false
  require_base: false
  require_head: true

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
