from datetime import timedelta
from typing import Any, Final, final
from weakref import ReferenceType

class AwsCredential:
    @final
    class Default(AwsCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> AwsCredential.Default: ...
    @final
    class EnvironmentVariable(AwsCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> AwsCredential.EnvironmentVariable: ...
    @final
    class Key(AwsCredential):
        __match_args__: Final = ("access_key_id", "secret_access_key")
        def __new__(cls, /, access_key_id: str, secret_access_key: str) -> AwsCredential.Key: ...
        @property
        def access_key_id(self, /) -> str: ...
        @property
        def secret_access_key(self, /) -> str: ...
    @final
    class ProfileFile(AwsCredential):
        __match_args__: Final = ("profile_name",)
        def __new__(cls, /, profile_name: str |None = None) -> AwsCredential.ProfileFile: ...
        @property
        def profile_name(self, /) -> str |None: ...
    @final
    class Session(AwsCredential):
        __match_args__: Final = ("access_key_id", "secret_access_key", "session_token")
        def __new__(cls, /, access_key_id: str, secret_access_key: str, session_token: str) -> AwsCredential.Session: ...
        @property
        def access_key_id(self, /) -> str: ...
        @property
        def secret_access_key(self, /) -> str: ...
        @property
        def session_token(self, /) -> str: ...

@final
class AwsSecretsManagerSettingsProvider(SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class AwsSecretsManagerSettingsSource(SettingsSource):
    def __new__(cls, /, secret_id: str, credential: AwsCredential, region: str |None = None, url: str |None = None) -> AwsSecretsManagerSettingsSource: ...
    def build(self, /) -> SettingsProvider: ...

@final
class AzureAppConfigurationSettingsProvider(SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class AzureAppConfigurationSettingsSource(SettingsSource):
    def __new__(cls, /, endpoint: str, credential: AzureCredential) -> AzureAppConfigurationSettingsSource: ...
    def build(self, /) -> SettingsProvider: ...

class AzureCredential:
    @final
    class AzureCli(AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> AzureCredential.AzureCli: ...
    @final
    class AzureDeveloperCli(AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> AzureCredential.AzureDeveloperCli: ...
    @final
    class ClientSecret(AzureCredential):
        __match_args__: Final = ("tenant_id", "client_id", "client_secret")
        def __new__(cls, /, tenant_id: str, client_id: str, client_secret: str) -> AzureCredential.ClientSecret: ...
        @property
        def client_id(self, /) -> str: ...
        @property
        def client_secret(self, /) -> str: ...
        @property
        def tenant_id(self, /) -> str: ...
    @final
    class Default(AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> AzureCredential.Default: ...
    @final
    class ManagedIdentityCredential(AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> AzureCredential.ManagedIdentityCredential: ...
    @final
    class WorkloadIdentityCredential(AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> AzureCredential.WorkloadIdentityCredential: ...

@final
class AzureKeyVaultSettingsProvider(SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class AzureKeyVaultSettingsSource(SettingsSource):
    def __new__(cls, /, url: str, credential: AzureCredential, reload_interval: timedelta |None = None) -> AzureKeyVaultSettingsSource: ...
    def build(self, /) -> SettingsProvider: ...

@final
class EnvironmentVariablesSettingsProvider(SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class EnvironmentVariablesSettingsSource(SettingsSource):
    def __new__(cls, /) -> EnvironmentVariablesSettingsSource: ...
    def build(self, /) -> SettingsProvider: ...

@final
class GcpSecretManagerSettingsProvider(SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class GcpSecretManagerSettingsSource(SettingsSource):
    def __new__(cls, /, project_id: str, credentials_json: str |None = None) -> GcpSecretManagerSettingsSource: ...
    def build(self, /) -> SettingsProvider: ...

@final
class JsonFileSettingsProvider(SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class JsonFileSettingsSource(SettingsSource):
    def __new__(cls, /, content_root_path: str |None, path: str, optional: bool, reload_on_change: bool) -> JsonFileSettingsSource: ...
    def build(self, /) -> SettingsProvider: ...

@final
class ModelRegistry:
    def __new__(cls, /, reload_models_callback: ReferenceType) -> ModelRegistry: ...
    def add_model(self, /, model: Any, section_path: str |None = None) -> None:
        """
        Adds a Pydantic model to the registry
        """
    def models(self, /) -> "list[RegisteredModel]":
        """
        Returns all tracked Pydantic models. It will automatically remove models that have been garbage collected.
        """

@final
class RegisteredModel:
    @property
    def model_reference(self, /) -> ReferenceType: ...
    @property
    def section_path(self, /) -> str |None: ...

class SettingLookup:
    @final
    class Found(SettingLookup):
        __match_args__: Final = ("value",)
        def __new__(cls, /, value: str |None) -> SettingLookup.Found: ...
        @property
        def value(self, /) -> str |None: ...
    @final
    class Missing(SettingLookup):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> SettingLookup.Missing: ...

@final
class SettingPerFileSettingsProvider(SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class SettingPerFileSettingsSource(SettingsSource):
    def __new__(cls, /, directory_path: str, optional: bool, reload_on_change: bool) -> SettingPerFileSettingsSource: ...
    def build(self, /) -> SettingsProvider: ...

@final
class SettingsPath:
    KEY_DELIMITER: Final = "."
    @staticmethod
    def get_section_key(path: str) -> str:
        """
        Returns the last section key from a given settings path.
        If the path does not contain the delimiter, it returns the original path.
        """

class SettingsProvider:
    """
    Provides setting values
    """
    def __new__(cls, /) -> SettingsProvider: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

class SettingsSource:
    """
    Source of setting values
    """
    def __new__(cls, /) -> SettingsSource: ...
    def build(self, /) -> SettingsProvider: ...

@final
class YamlFileSettingsProvider(SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class YamlFileSettingsSource(SettingsSource):
    def __new__(cls, /, content_root_path: str |None, path: str, optional: bool, reload_on_change: bool) -> YamlFileSettingsSource: ...
    def build(self, /) -> SettingsProvider: ...
