from typing import Final, final

@final
class ConventionChanger:
    @staticmethod
    def to_snake_case(string_to_convert: str) -> str:
        """
        Convert a `PascalCase`, `camelCase`, or `kebab-case` string to `snake_case`.
        """

@final
class PythonAwsSecretsManagerSettingsProvider:
    def __new__(cls, /, secret_id: str, region: str |None = None, url: str |None = None, access_key_id: str |None = None, secret_access_key: str |None = None, session_token: str |None = None, profile: str |None = None) -> PythonAwsSecretsManagerSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load(self, /) -> None: ...

@final
class PythonAzureKeyVaultSettingsProvider:
    def __new__(cls, /, url: str, client_id: str |None = None, client_secret: str |None = None, tenant_id: str |None = None) -> PythonAzureKeyVaultSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load(self, /) -> None: ...

@final
class PythonEnvironmentVariablesSettingsProvider:
    def __new__(cls, /) -> PythonEnvironmentVariablesSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    async def load(self, /) -> None: ...

@final
class PythonGcpSecretManagerSettingsProvider:
    def __new__(cls, /, project_id: str, credentials_json: str |None = None) -> PythonGcpSecretManagerSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load(self, /) -> None: ...

@final
class PythonJsonFileSettingsProvider:
    def __new__(cls, /, content_root_path: str |None, path: str, optional: bool) -> PythonJsonFileSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load(self, /) -> None: ...

@final
class PythonKeyPerFileSettingsProvider:
    def __new__(cls, /, directory_path: str, optional: bool) -> PythonKeyPerFileSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load(self, /) -> None: ...

@final
class PythonYamlFileSettingsProvider:
    def __new__(cls, /, content_root_path: str |None, path: str, optional: bool) -> PythonYamlFileSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load(self, /) -> None: ...

@final
class SettingsPath:
    KEY_DELIMITER: Final = "."
    @staticmethod
    def get_section_key(path: str) -> str: ...
