from typing import Any, Final, final

@final
class AwsSecretsManagerSettingsProvider(SettingsProvider):
    def __new__(cls, /, secret_id: str, region: str |None = None, url: str |None = None, access_key_id: str |None = None, secret_access_key: str |None = None, session_token: str |None = None, profile: str |None = None) -> AwsSecretsManagerSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load_sync(self, /) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class AzureKeyVaultSettingsProvider(SettingsProvider):
    def __new__(cls, /, url: str, client_id: str |None = None, client_secret: str |None = None, tenant_id: str |None = None) -> AzureKeyVaultSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load_sync(self, /) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class EnvironmentVariablesSettingsProvider(SettingsProvider):
    def __new__(cls, /) -> EnvironmentVariablesSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load_sync(self, /) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class GcpSecretManagerSettingsProvider(SettingsProvider):
    def __new__(cls, /, project_id: str, credentials_json: str |None = None) -> GcpSecretManagerSettingsProvider: ...
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load_sync(self, /) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class JsonFileSettingsProvider(SettingsProvider):
    def __new__(cls, /, content_root_path: str |None, path: str, optional: bool) -> JsonFileSettingsProvider:
        """
        Creates a JSON settings provider from a path.
        
        The `path` argument can be:
        - A file name (for example, `settings.json`).
        - A relative path (for example, `config/settings.json`).
        - An absolute path (for example, `/tmp/settings.json`).
        
        File names and relative paths are resolved against `content_root_path` when provided, otherwise against the current working directory.
        """
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load_sync(self, /) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class KeyPerFileSettingsProvider(SettingsProvider):
    def __new__(cls, /, directory_path: str, optional: bool) -> KeyPerFileSettingsProvider:
        """
        Adds settings using files from a directory. File names are used as the key, file contents are used as the value.
        """
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load_sync(self, /) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

class SettingLookup:
    @final
    class Found(SettingLookup):
        __match_args__: Final = ("value",)
        def __new__(cls, /, value: str |None) -> SettingLookup.Found: ...
        @property
        def value(self, /) -> str |None: ...
    @final
    class Missing(SettingLookup):
        __match_args__: Final = ()
        def __getitem__(self, /, key: int) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> SettingLookup.Missing: ...

@final
class SettingsPath:
    KEY_DELIMITER: Final = "."
    @staticmethod
    def get_section_key(path: str) -> str:
        """
        Returns the last section key from a given settings path.
        If the path does not contain the delimiter, it returns the original path.
        """

class SettingsProvider:
    """
    Provides setting values
    """
    def __new__(cls, /) -> SettingsProvider: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load_sync(self, /) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...

@final
class YamlFileSettingsProvider(SettingsProvider):
    def __new__(cls, /, content_root_path: str |None, path: str, optional: bool) -> YamlFileSettingsProvider:
        """
        Creates a YAML settings provider from a path.
        
        The `path` argument can be:
        - A file name (for example, `settings.yaml`).
        - A relative path (for example, `config/settings.yaml`).
        - An absolute path (for example, `/tmp/settings.yaml`).
        
        File names and relative paths are resolved against `content_root_path` when provided, otherwise against the current working directory.
        """
    def __str__(self, /) -> str: ...
    @property
    def data(self, /) -> dict[str, str |None]: ...
    def load_sync(self, /) -> None: ...
    def try_get(self, /, key: str) -> SettingLookup: ...
