from typing import Any, Final, final

class _AwsCredential:
    @final
    class Default(_AwsCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> _AwsCredential.Default: ...
    @final
    class EnvironmentVariable(_AwsCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> _AwsCredential.EnvironmentVariable: ...
    @final
    class Key(_AwsCredential):
        __match_args__: Final = ("access_key_id", "secret_access_key")
        def __new__(cls, /, access_key_id: str, secret_access_key: str) -> _AwsCredential.Key: ...
        @property
        def access_key_id(self, /) -> str: ...
        @property
        def secret_access_key(self, /) -> str: ...
    @final
    class ProfileFile(_AwsCredential):
        __match_args__: Final = ("profile_name",)
        def __new__(cls, /, profile_name: str |None = None) -> _AwsCredential.ProfileFile: ...
        @property
        def profile_name(self, /) -> str |None: ...
    @final
    class Session(_AwsCredential):
        __match_args__: Final = ("access_key_id", "secret_access_key", "session_token")
        def __new__(cls, /, access_key_id: str, secret_access_key: str, session_token: str) -> _AwsCredential.Session: ...
        @property
        def access_key_id(self, /) -> str: ...
        @property
        def secret_access_key(self, /) -> str: ...
        @property
        def session_token(self, /) -> str: ...
