from .aws_identity import _AwsCredential
from .core import _ModelRegistry, _SettingLookup, _SettingsProvider, _SettingsSource
from typing import final

@final
class _AwsSecretsManagerSettingsProvider(_SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: _ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> _SettingLookup: ...

@final
class _AwsSecretsManagerSettingsSource(_SettingsSource):
    def __new__(cls, /, secret_id: str, credential: _AwsCredential, region: str |None = None, url: str |None = None) -> _AwsSecretsManagerSettingsSource: ...
    def build(self, /) -> _SettingsProvider: ...
