from typing import Any, Final, final

class _AzureCredential:
    @final
    class AzureCli(_AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> _AzureCredential.AzureCli: ...
    @final
    class AzureDeveloperCli(_AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> _AzureCredential.AzureDeveloperCli: ...
    @final
    class ClientSecret(_AzureCredential):
        __match_args__: Final = ("tenant_id", "client_id", "client_secret")
        def __new__(cls, /, tenant_id: str, client_id: str, client_secret: str) -> _AzureCredential.ClientSecret: ...
        @property
        def client_id(self, /) -> str: ...
        @property
        def client_secret(self, /) -> str: ...
        @property
        def tenant_id(self, /) -> str: ...
    @final
    class Default(_AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> _AzureCredential.Default: ...
    @final
    class ManagedIdentity(_AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> _AzureCredential.ManagedIdentity: ...
    @final
    class WorkloadIdentity(_AzureCredential):
        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> _AzureCredential.WorkloadIdentity: ...
