from .azure_identity import _AzureCredential
from .core import _ModelRegistry, _SettingLookup, _SettingsProvider, _SettingsSource
from datetime import timedelta
from typing import final

@final
class _AzureKeyVaultSettingsProvider(_SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: _ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> _SettingLookup: ...

@final
class _AzureKeyVaultSettingsSource(_SettingsSource):
    def __new__(cls, /, uri: str, credential: _AzureCredential, reload_enabled: bool = False, reload_interval: timedelta |None = None) -> _AzureKeyVaultSettingsSource: ...
    def build(self, /) -> _SettingsProvider: ...
