from .core import _ModelRegistry, _SettingLookup, _SettingsProvider, _SettingsSource
from typing import final

@final
class _GcpSecretManagerSettingsProvider(_SettingsProvider):
    def __str__(self, /) -> str: ...
    def data(self, /) -> "dict[str, str | None]": ...
    def load(self, /) -> None: ...
    def set_model_registry(self, /, model_registry: _ModelRegistry) -> None: ...
    def try_get(self, /, key: str) -> _SettingLookup: ...

@final
class _GcpSecretManagerSettingsSource(_SettingsSource):
    def __new__(cls, /, project_id: str, credentials_json: str |None = None) -> _GcpSecretManagerSettingsSource: ...
    def build(self, /) -> _SettingsProvider: ...
